ITSGestion/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url

from django.conf import settings
from ITSGestion import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Solcito.urls', namespace = "Solcito")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Solcito/urls.py
from django.conf.urls import patterns, include, url
from Solcito import views, docentes_views, ordenes_de_merito

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^registration/$', views.index, name='index'),
    url(r'^submit_matricula/$', views.submitMatricula, name='submit_matricula'),
    url(r'^login/$', views.logMeIn, name='login'),
    url(r'^logout/$', views.logMeOut, name='logout'),
    url(r'^genpdf/(?P<id_student>[0-9]+)/$', views.genpdf, name="genpdf"),
    url(r'^confirm_matricula/$', views.confirmMatricula, name='confirm_matricula'),
    url(r'^docentes/$', docentes_views.docentes, name="docentes"),
    url(r'^materias/$', docentes_views.materias, name="materias"),
    url(r'^get_by_materia/$', docentes_views.get_by_materia, name="get_by_materia"),
    url(r'^getexcel/$', docentes_views.getSubjectExcel, name="get_excel"),
    url(r'^clean_excel/$', docentes_views.cleanExcel, name="clean_excel"),
    url(r'^excel/$', docentes_views.excel, name="excel"),
    url(r'^oredenes_de_merito/$', ordenes_de_merito.oredenes_de_merito, name="oredenes_de_merito"),
    url(r'^ordenar/$', ordenes_de_merito.ordenar, name="ordenar"),
]

Solcito/forms.py
 # -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from Solcito.models import RegistrationS, Student, Tutor, Teacher
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext, ugettext_lazy as _
from django.forms.utils import ErrorList
from material import *



class RegistrationSForm(ModelForm):

    layout = Layout(
        Row(Span6('activeDate')),Span6('desactiveDate'),
        Row(Span12('student')),
        Row(Span12('curso')),
    )

    class Meta:
        model = RegistrationS
        exclude = ('idRegistrationS',)

class TeacherForm(ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.CharField(
        label=_("username"),
        strip=False,
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    class Meta:
        model = Teacher
        exclude = ('idteacher',)

    def clean(self):
        '''
        Check forms errors
        '''
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            self.add_error('password1', 'Please, input the same password')
            self.add_error('password2', 'Please, input the same password')

        try:
            u = User.objects.get(username=cleaned_data.get("username"))
            self.add_error('username', 'This username is alredy in use')
        except:
            pass

    def save(self, commit=True):
        #Create user
        cleaned_data = self.cleaned_data
        user = User(username=cleaned_data.get("username"),
                    is_staff=True)

        user.set_password(cleaned_data["password1"])
        user.save()
        if cleaned_data['tipo'] == "teacher":
            group = Group.objects.get(name='Docente')
            user.groups.add(group)
        elif cleaned_data['tipo'] == "celador":
            group = Group.objects.get(name='Preceptor')
            user.groups.add(group)
        #create teacher
        try:
            instance = super(TeacherForm, self).save(commit=False)
            instance.authuser = user
            if commit:
                instance.save()
        except:
            user.delete()
        return instance


class EditRegistrationForm(forms.ModelForm):

    error_css_class = 'alert alert-danger'

    class Meta:

        model = Student
        exclude = ('idStudent', 'photo')


    def __init__(self, *args, **kwargs):
        super(EditRegistrationForm, self).__init__(*args, **kwargs)
        for (field_name, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field.required:
                field.widget.attrs['placeholder'] = 'Requerido'
                field.label = '* ' + field.label



class StudentForm(ModelForm):

    layout = Layout(
        Row(Span6('name'), Span6('lastName')),
        Row(Span6('email'),Span3('dni'), Span3('sex')),
        Row(Span4('landline'), Span4('cellphone'),Span4('birthDate')),
        Row('religion', 'birthPlace', 'nacionality'),
        Row(Span5('street'), Span5('neighborhood'), Span2('numberStreet')),
        Row(Span3('PC'), Span3('tower'), Span3('floorDepartment'), Span3('department')),
    )

    class Meta:
        model = Student
        exclude = ('idStudent', 'photo','curso')

    def clean(self):
        cleaned_data = self.cleaned_data
        print (cleaned_data)
        try:
            birthDate = cleaned_data.get("birthDate")
        except:
            birthDate = None
        if not birthDate:
            self.add_error('birthDate', 'Este campo es obligatorio')
        try:
            landline = cleaned_data.get("landline")
        except:
            pass

        try:
            cellphone = cleaned_data.get("cellphone")
        except:
            pass

        if landline != None:
            lenphone = len(str(landline))
        else:
            lenphone = 0
        if cellphone != None:
            len_cell = len(str(cellphone))
        else:
            len_cell = 0
        if lenphone < 7 and len_cell < 7 :
            msg = "Por favor, ingrese al menos un número telefónico válido."
            self.add_error('landline', msg)
            self.add_error('cellphone', msg)


class GuardianForm(ModelForm):
    layout = Layout(
        Row(Span6('name'), Span6('lastName')),
        Row(Span4('email'), Span4('dni'), Span4('cuil')),
        Row('locality' , 'nacionality'),
        Row(Span4('landline'), Span4('cellphone'), Span4('workPhone')),
        Row(Span6('profession'), Span6('workPlace')),
        Row(Span5('street'), Span5('neighborhood'), Span2('numberStreet')),
        Row(Span3('PC'), Span3('tower'), Span3('floorDepartment'), Span3('department')),
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        print (cleaned_data)
        try:
            landline = cleaned_data.get("landline")
        except:
            pass

        try:
            cellphone = cleaned_data.get("cellphone")
        except:
            pass

        if landline != None:
            lenphone = len(str(landline))
        else:
            lenphone = 0
        if cellphone != None:
            len_cell = len(str(cellphone))
        else:
            len_cell = 0
        if lenphone < 7 and len_cell < 7 :
            msg = "Por favor, ingrese al menos un número telefónico válido."
            self.add_error('landline', msg)
            self.add_error('cellphone', msg)

    class Meta:
        model = Tutor
        exclude = ('students','rol','children')



class UploadForm(forms.Form):
    docfile = forms.FileField(
        label='Selecciona un archivo'
    )

Solcito/views.py
from django.views.decorators.http import require_POST, require_GET
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from Solcito.models import Student, RegistrationS, Tutor
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from Solcito.forms import EditRegistrationForm
from django.template.loader import render_to_string
import logging
#PDF
import cStringIO as StringIO
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape

from .forms import StudentForm, GuardianForm

logger = logging.getLogger('django')

def logMeIn(request): #Logueo
    context = RequestContext(request)
    errors = []
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user) #logueo de usuario por defecto de django
                return redirect('/')
        else:
            errors.append(u"El usuario o la contrasena son incorrectos")
    return render_to_response('login.html',
                              {'errors':errors},
                              context)

def logMeOut(request):
    logout(request) #Logout de django
    context = RequestContext(request)
    return redirect('/')

def home(request):
    context = RequestContext(request)
    return render_to_response('index.html',context)

@require_GET
def index(request):
    context = RequestContext(request)
    student = Student()
    father = Tutor()
    mother = Tutor()
    tutor = Tutor()
    context['student_form']= StudentForm(instance = student)
    context['father_form']= GuardianForm(instance = father, prefix="father")
    context['mother_form']= GuardianForm(instance = mother, prefix="mother")
    context['guardian_form']= GuardianForm(instance = tutor, prefix="tutor")
    return render_to_response('matricular.html',{},context)


#https://github.com/eliluminado/esCUITValida/blob/master/esCUITValida.py
@require_POST
def confirmMatricula(request):
    context = RequestContext(request)

    sf = StudentForm(request.POST)
    ff= GuardianForm(request.POST, prefix='father')
    mf= GuardianForm(request.POST, prefix='mother')
    gf= GuardianForm(request.POST, prefix='tutor')

    if (sf.is_valid()):
        print "SUCCESS WITH STUDENT"
        if (ff.is_valid() or mf.is_valid() or gf.is_valid()):
            print "SUCCESS WITH TUTORS"
            context['valid'] = "true"
        else:
            context['valid'] = "false"
            print "ERRORSS!!!!!"
            print (ff.errors)
            print (mf.errors)
            print (gf.errors)
    else:
        context['valid'] = "false"
        print (sf.errors)

    diccionario = dict(request.POST)
    for element in diccionario:
        if "father" in element:
            diccionario[element.replace("father-", "f")] = diccionario.pop(element)
        if "mother" in element:
            diccionario[element.replace("mother-", "m")] = diccionario.pop(element)
        if "tutor" in element:
            diccionario[element.replace("tutor-", "g")] = diccionario.pop(element)


    context['student_form']= sf
    context['father_form']= ff
    context['mother_form']= mf
    context['guardian_form']= gf
    return render_to_response('matricular.html',{'data':diccionario},context)

def submitMatricula(request):
    context = RequestContext(request)
    if request.method=='POST':
        try:
            si = Student.objects.get(dni=request.POST['dni'])
        except:
            si = Student()
        try:
            fi = Tutor.objects.get(dni=request.POST['father-dni'])
        except:
            fi = Tutor(rol="Father")
        try:
            mi = Tutor.objects.get(dni=request.POST['mother-dni'])
        except:
            mi = Tutor(rol="Mother")
        try:
            ti = Tutor.objects.get(dni=request.POST['tutor-dni'])
        except:
            ti = Tutor(rol="Tutor")

        sf = StudentForm(request.POST, instance=si)
        ff= GuardianForm(request.POST, instance=fi, prefix='father')
        mf= GuardianForm(request.POST, instance=mi, prefix='mother')
        gf= GuardianForm(request.POST, instance=ti, prefix='tutor')

        if (sf.is_valid()):
            sf.save()
            if ff.is_valid():
                ff.save()
                ff.instance.children.add(si)
            if mf.is_valid():
                mf.save()
                mf.instance.children.add(si)
            if gf.is_valid():
                gf.save()
                gf.instance.children.add(si)
            student = Student.objects.get(dni=request.POST['dni'])
            student.active = False
            return redirect('/genpdf/'+str(student.pk))

        else:
            print ("ERRORES!!!")
            print (sf.errors)

            context['student_form']= sf
            context['father_form']= ff
            context['mother_form']= mf
            context['tutor_form']= gf
            return render_to_response('matricular.html',{},context)

        #return render_to_response('matricula_success.html',{},context)
    return render_to_response('matricular_bug.html',{},context)

def html2pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()
    print "render"

    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(),
            content_type='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

def genpdf(request,id_student):
    print "ARG"
    print id_student
    student = Student.objects.get(pk=id_student)
    #Retrieve data or whatever you need
    return html2pdf(
        'pdf.html',
        {
            'pagesize':'A4',
            'student':student
        }
    )

Solcito/templates/clean_excel.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}







{% block content %}
<form action="{% url 'Solcito:get_excel' %}" method="get" enctype="multipart/form-data">
        {% csrf_token %}
        <select name="materia">
            {% for subject in subjects %}
                <option value="{{ subject.pk }}">{{ subject.name }}</option>
            {% endfor %}
        </select>

        <input type="submit" value="Submit">
    </form>

</div>
    <div class="contac" id="lista">
        <div>
            <ul class="list">
            {% for i in rows %}
                <li>{{ i.2 }}</li>
            {% endfor %}
            </ul>
        </div>
        <div>
            <ul class="list">
            {% for i in rows %}
                <li>{{ i.7 }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>

</body>
{% endblock %}

Solcito/templates/docentes.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}







{% block content %}
<form action="{% url 'Solcito:excel' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="FILE" name="docfile">
        <select name="materia">
            {% for matricula in matriculas %}
                <option value="{{ matricula.subject.pk }}">{{ matricula.subject.name }}</option>
            {% endfor %}
        </select>
        <select name="trimestre">

            {% for trimestre in trimestres %}
                <option value="{{ trimestre.0 }}">{{ trimestre.1 }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Submit">
    </form>

</div>
    <div class="contac" id="lista">
        <div>
            <ul class="list">
            {% for i in rows %}
                <li>{{ i.2 }}</li>
            {% endfor %}
            </ul>
        </div>
        <div>
            <ul class="list">
            {% for i in rows %}
                <li>{{ i.7 }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>

</body>
{% endblock %}

Solcito/templates/index.html
{% load staticfiles %}

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title> SUN - ITS Gestión </title>
        <link href="Ingresar%20ITSV_files/estetica.css" rel="stylesheet" type="text/css">
        <link href="{% static 'css/materialize.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body background="{% static 'img/cole.jpg' %}" style="background-size: cover; background-repeat: no-repeat;">

        <div class="navbar row" style="margin-top:3%;height:150px;">
            <nav class="nav-wrapper container" style="background:rgba(64,224,208,0.8); height:150px;">
                <div class="col s12 m4 l2" align="right" style="margin-top:45px;">
                    <img class="responsive-img" src="../static/img/cole.png" style="height:65px;">
                </div>
                <div class="col s12 m4 l8" align="center" style="margin-top:10px;">
                    <h4 class="thin">INSTITUTO TÉCNICO SALESIANO</h4>
                    <h4 class="thin">VILLADA</h4>
                </div>
                <div class="col s12 m4 l2" align="left" style="margin-top:25px;">
                    <img alt="" class="responsive-img" src="../static/img/sunlogo.png" style="height:100px;">
                </div>
            </nav>
        </div>

        <div class="row container z-depth-2" style="background:rgba(255, 255, 255, 0.5);">
            <div class="col s8 offset-s2">

                <h1 class="thin" align="center">Selecciona una opción</h1>
                    
                    <div class="card medium" style="margin-top:5%;">
                        <div class="card-image waves-effect waves-block waves-light">
                            <img class="activator" src="{% static 'img/stu.jpg' %}">
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">Matriculación<i class="material-icons right">more_vert</i></span>
                            <p><a href="{% url 'Solcito:index' %}">Matricular alumno</a></p>
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">Matriculación<i class="material-icons right">close</i></span>
                            <p>Complete el formulario con los datos del alumno y al menos un tutor legal. El formulario se cargará automáticamente a la página y el alumno ya estara registrado en nuestra base de datos.</p>
                        </div>
                    </div>

                    <div class="card medium" style="margin-top:5%;">
                        <div class="card-image waves-effect waves-block waves-light">
                            <img class="activator" src="{% static 'img/prof.jpg' %}">
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">Ingreso para Personal<i class="material-icons right">more_vert</i></span>
                            <p><a href="{% url 'admin:index' %}">Ingresar</a></p>
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">Ingreso para Personal<i class="material-icons right">close</i></span>
                            <p>Por este medio los profesores/preceptores pueden cargar las notas de los alumnos y registrar sus inasistencias o sanciones.  </p>
                        </div>
                    </div>


                    <div class="card medium" style="margin-top:5%;" style="margin:1%;">
                        <div class="card-image waves-effect waves-block waves-light">
                            <img class="activator" src="{% static 'img/av.jpg' %}">
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
                            <p><a href="edu.itsvillada.com.ar">This is a link</a></p>
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
                            <p>Here is some more information about this product that is only revealed once clicked on.</p>
                        </div>
                    </div>

                </div>
            </div>

    </body>

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>

</html>

Solcito/templates/materias.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}







{% block content %}

        <select name="materia" id="materia">
            {% for materia in materias %}
                <option value="{{ materia.pk }}">{{ materia.name }}</option>
            {% endfor %}
        </select>
        <button class="btn btn-primary" id="students">Planilla</button>

    <div id="results_list">
        </div>
    <script>
        $('#students').click(function(){
            data = {};
            data.materia = $('#materia').val();
            $.ajax(
                {
                    url: "{% url 'Solcito:get_by_materia' %}",
                    data : data,
                    success: function(result){
                        $("#results_list").html(result);
                    }
                }
            );
        });
    </script>
{% endblock %}

Solcito/templates/matricular.html
{% load static %}
{% load staticfiles %}
{% load material_form %}

<html lang="es">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Solcito</title>

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'css/materialize.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

        <!-- Custom Fonts -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <style>
            @media(min-width:768px) {
                .side-nav {
                    position: fixed;
                    top: 51px;
                    left: 225px;
                    width: 0px;
                    margin-left: -225px;
                    border: none;
                    border-radius: 0;
                    overflow-y: auto;
                    background-color: #222;
                    bottom: 0;
                    overflow-x: hidden;
                    padding-bottom: 40px;
                }

                .side-nav>li>ul {
                    padding: 0;
                }

                .side-nav>li>ul>li>a {
                    display: block;
                    padding: 10px 15px 10px 38px;
                    text-decoration: none;
                    color: #999;
                }

                .side-nav>li>ul>li>a:hover {
                    color: #fff;
                }
                @media(min-width:768px) {
                    #wrapper {
                        padding-left: 0px;
                    }

                    #page-wrapper {
                        padding: 0px;
                    }
                }
        </style>
    </head>

    <body>
        <div class="navbar-fixed row">
            <nav class="nav-wrapper cyan">
                <div class="col s1">
                    <img alt="" class="responsive-img" src="../static/img/sunlogo.png" style="height:65px;">
                </div>
                <div class="col s11" align="right">
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a href="{% url 'Solcito:login' %}" ><i class="fa fa-fw fa-user"></i> Iniciar Sesión</a></li>
                    </ul>
                </div>
            </nav>
        </div>

        <div class="valign-wrapper" id="formulario">

            <!--Aca va lo nuestro-->
            <div class="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col s12">

                            <form action="{% url 'Solcito:confirm_matricula' %}" method="POST" id="matForms">
                                {% csrf_token %}
                                <div class="col s6">
                                    <h4 align="center">Datos del Alumno</h4>
                                    <br>
                                    {% form form=student_form %}{% endform %}
                                </div>
                                <div class="col s6">
                                    <h4 align="center">Datos de los Padres</h4>
                                    <br>

                                    <ul class="collapsible" data-collapsible="accordion">
                                        <li>
                                            <div class="collapsible-header active">Folmulario Padre</div>
                                            <div class="collapsible-body">

                                                <div class="panel-body">
                                                    {% form form=father_form %}{% endform %}
                                                </div>

                                            </div>
                                        </li>
                                        <li>
                                            <div class="collapsible-header">Formulario Madre</div>
                                            <div class="collapsible-body">

                                                <div class="panel-body">
                                                    {% form form=mother_form %}{% endform %}
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="collapsible-header">Formulario Tutor</div>
                                            <div class="collapsible-body">
                                                <div class="panel-body">
                                                    {% form form=guardian_form %}{% endform %}
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col s12" align="right">
                                    <div class="panel-heading">
                                        <div class="col s12" align="right">
                                            <div class="panel-heading">
                                                <input id="confirm_matricula" type="submit" value="Confirmar" class="btn btn-primary btn-lg">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>

                            <form action="{% url 'Solcito:confirm_matricula' %}" method="POST">
                                {% csrf_token %}
                                <div class="col s6">
                                    {% form form=photo_form %}{% endform %}
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="dismatricula">
            {% include "dismatricula.html" %}
        </div>
    </body>

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/materialize.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script>

        $(document).ready(function(){
            if("{{valid}}"=="true"){
                $('#formulario').hide();
            }else{
                $('#dismatricula').hide();
            }

            $('select').material_select();


            $('.collapsible').collapsible({
                accordion : false
            });
        });

        /*previsualisacion de foto*/
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#alum').attr('src', e.target.result);
                }
            }
        }

        $('#photo').change(function(){
            readURL(this);
        });

        $("input[data-form-control='date']").pickadate({
            // Strings and translations
            monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Dicembre'],
            monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
            weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mier', 'Jue', 'Vie', 'Sab'],
            showMonthsShort: undefined,
            showWeekdaysFull: undefined,

            // Buttons
            today: 'Hoy',
            clear: 'Borrar',
            close: 'Cerrar',

            // Accessibility labels
            labelMonthNext: 'Mes siguiente',
            labelMonthPrev: 'Mes anterior',
            labelMonthSelect: 'Seleccione mes',
            labelYearSelect: 'Selecciones año',

            formatSubmit: 'dd/mm/yyyy',
            format: 'dd/mm/yyyy',
            selectMonths: true,
            selectYears: 100,
            closeOnSelect: true,
            max: true,
            onSet: function(context) {
                $('#id_birth_date').close();
            }
        });


    </script>
</html>

Solcito/templates/matricular_bug.html
Fail

Solcito/templates/matricular_foto.html
Archivo excede el peso de 5 mb / La imagen no se guardo